import './globals.css'
import { Inter } from 'next/font/google'
import Admin_Header from "@/app/admin/components/Admin_Header.jsx"
import Admin_Sidebar from './admin/components/Admin_Sidebar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Admin Panel - Book Store',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}><Admin_Header />
                <div className='flex justify-center flex-1 '>
                    <div className="w-2/12">
                        <Admin_Sidebar />
                    </div>
                    <div className="w-10/12">
                        {children}
                    </div>
                </div>
            </body>
        </html>
    )
}
